"""Check data, checkpoint, and results integrity.

Usage: python scripts/0_check_integrity.py
"""
import sys, json, numpy as np
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from obscodec.config import DATA_DIR, ASSETS_DIR, CHECKPOINT_DIR


def check_data():
    """Verify all .npy data files exist and have correct shapes."""
    print("=== Data Files ===")
    expected = {
        "simple_spread_obs.npy": (33333, 30),
        "simple_tag_obs.npy": (33333, 24),
        "simple_world_comm_obs.npy": (33333, 36),
        "tag_hd_obs.npy": (33333, 40),
        "spread_hd_obs.npy": (33333, 48),
        "comm_hd_obs.npy": (33333, 60),
        "spread_xhd_obs.npy": (33333, 90),
        "spread_N3_obs.npy": (33333, 18),
        "spread_N5_obs.npy": (33333, 30),
        "spread_N7_obs.npy": (33333, 42),
        "spread_N10_obs.npy": (33333, 60),
        "spread_N12_obs.npy": (33333, 72),
        "spread_N15_obs.npy": (33333, 90),
    }
    all_ok = True
    for fname, expected_shape in expected.items():
        path = DATA_DIR / fname
        if path.exists():
            data = np.load(str(path))
            shape_ok = len(data.shape) == 2 and data.shape[0] == expected_shape[0] and data.shape[1] == expected_shape[1]
            status = "OK" if shape_ok else f"BAD SHAPE: {data.shape} expected {expected_shape}"
            if not shape_ok:
                all_ok = False
        else:
            status = "MISSING"
            all_ok = False
        print(f"  {fname:<30} {status}")
    return all_ok


def check_results():
    """Verify all results JSON files are valid."""
    print("\n=== Results JSONs ===")
    expected = [
        "pca_results.json", "ae_results.json", "digital_results.json",
        "vae_results.json", "vae_hd_scaling_results.json",
        "vqvae_results.json",
        "collapse_barrier_results.json", "collapse_barrier_full_results.json",
        "fb_cross_scenario_validation.json", "pilot_channel_results.json",
        "fb_finesweep_results.json", "agent_scaling_results.json",
        "vqvae_multiscenario_results.json", "unified_codec_results.json",
    ]
    # Phase 3 JSONs — generated by running Phase 3 experiment scripts
    phase3_optional = [
        "diff_channel_results.json", "jscc_results.json",
        "task_aware_results.json", "e2e_results.json",
    ]
    all_ok = True
    for fname in expected:
        path = ASSETS_DIR / fname
        if path.exists():
            with open(path) as f:
                data = json.load(f)
            status = f"OK ({len(data)} entries)" if isinstance(data, list) else "OK"
        else:
            status = "MISSING"
            all_ok = False
        print(f"  {fname:<40} {status}")
    for fname in phase3_optional:
        path = ASSETS_DIR / fname
        if path.exists():
            with open(path) as f:
                data = json.load(f)
            status = f"OK ({len(data)} entries)" if isinstance(data, list) else "OK"
        else:
            status = "PENDING (run Phase 3 script to generate)"
        print(f"  {fname:<40} {status}")
    return all_ok


def check_checkpoints():
    """Verify checkpoints directory exists."""
    print("\n=== Checkpoints ===")
    if CHECKPOINT_DIR.exists():
        pts = list(CHECKPOINT_DIR.glob("*.pt"))
        print(f"  {len(pts)} .pt files in {CHECKPOINT_DIR}")
        return True
    else:
        print(f"  DIRECTORY MISSING: {CHECKPOINT_DIR}")
        return False


def check_figures():
    """Verify figure PNGs exist."""
    print("\n=== Figures ===")
    expected = [
        "rate_distortion_simple_spread.png",
        "rate_distortion_simple_tag.png",
        "rate_distortion_simple_world_comm.png",
        "rate_distortion_unified.png",
        "kl_beta_simple_spread.png",
        "kl_vs_beta_all_scenarios.png",
        "collapse_barrier_summary.png",
        "collapse_barrier_analysis.png",
        "fb_cross_scenario_validation.png",
    ]
    for fname in expected:
        path = ASSETS_DIR / fname
        status = "OK" if path.exists() else "MISSING"
        print(f"  {fname:<45} {status}")


def check_phase3():
    """Verify Phase 3 library and script files exist."""
    print("\n=== Phase 3: Semantic Communication ===")
    root = Path(__file__).resolve().parents[1]
    files = [
        "obscodec/channel/diff_channel.py",
        "obscodec/models/jscc.py",
        "obscodec/task_metrics.py",
        "obscodec/cost_metrics.py",
        "scripts/7_diff_channel.py",
        "scripts/8_jscc_training.py",
        "scripts/9_task_aware.py",
        "scripts/10_end_to_end.py",
    ]
    all_ok = True
    for rel_path in files:
        path = root / rel_path
        status = "OK" if path.exists() else "MISSING"
        if not path.exists():
            all_ok = False
        print(f"  {rel_path:<45} {status}")

    # Check Phase 3 config entries
    try:
        from obscodec.config import (JSCC_SCENARIOS, JSCC_BETAS, JSCC_LATENT_DIM,
                                      DIFF_AWGN_SNR_TRAIN, DIFF_ERASURE_RATES,
                                      TASK_LOSS_TYPES, TASK_WEIGHTS, E2E_ROLLOUT_STEPS)
        print(f"  Phase 3 config entries: OK")
    except ImportError as e:
        print(f"  Phase 3 config entries: MISSING ({e})")
        all_ok = False

    # Check Phase 3 imports
    try:
        from obscodec.channel.diff_channel import DiffAWGN, DiffErasure, DiffBlockErasure, DiffRayleighProxy
        from obscodec.models.jscc import JSCCWrapper
        from obscodec.task_metrics import evaluate_task_metrics, coordination_error, self_position_mse
        from obscodec.data.synthetic import generate_spread_with_metrics
        print(f"  Phase 3 imports: OK")
    except ImportError as e:
        print(f"  Phase 3 imports: FAILED ({e})")
        all_ok = False

    return all_ok


if __name__ == "__main__":
    print("ObsCodec Integrity Check\n")
    d = check_data()
    r = check_results()
    c = check_checkpoints()
    check_figures()
    p3 = check_phase3()

    print(f"\n{'='*50}")
    if d and r and c and p3:
        print("OVERALL: PASS")
    else:
        print("OVERALL: ISSUES FOUND")
        if not d:
            print("  - Data files missing/malformed")
        if not r:
            print("  - Results JSONs missing")
        if not c:
            print("  - Checkpoints directory missing")
        if not p3:
            print("  - Phase 3 files missing")
